### ISSUE TITLE
Vue support

### ISSUE THREAD

**Issue by catgoose** [llllvvuu/nvim-js-actions#1]
My config:

```lua
local js_filetypes = {
  "javascript",
  "javascriptreact",
  "typescript",
  "typescriptreact",
  "vue"
}

return {
  {
    "llllvvuu/nvim-js-actions",
    ft = js_filetypes,
    dependencies = { "nvim-treesitter/nvim-treesitter" },
    init = function()
      vim.api.nvim_create_autocmd(
        "FileType",
        {
          pattern = js_filetypes,
          command = "nnoremap <buffer> <leader>ta " ..
            ":lua require('nvim-js-actions').js_arrow_fn.toggle()<CR>"
            -- can also do `require('nvim-js-actions/js-arrow-fn').toggle()`
        }
      )
    end
  }
}
```

When I try to use the plugin within a vue file, the plugin warns: `Cursor is not in a function`.  For example:

```vue
<script setup lang="ts">
  const a = (b: string) => {
    console.log(b);
  }
</script>
```

**Comment by llllvvuu** [comment]
So one unfortunate thing here is that the function doesn't span the `const a =` part. I suppose I could look into having it scan downwards in the Treesitter tree.

If you have your cursor in the arrow function part then it works:

https://github.com/llllvvuu/nvim-js-actions/assets/5601392/a9d0591c-c6f1-449c-ae64-04abff7aea28

**Comment by catgoose** [comment]
Looks like I didn't have treesitter vue module installed.  Works great!  Though can we restore the cursor position after toggling?
